// How many stages the site shows. Stage 11 holds materials 12 to 16.
export const STAGE_COUNT = 11

// The value `current_stage` reaches once every stage is done. Nothing is rendered for it.
export const FINISHED_STAGE = STAGE_COUNT + 1

// The stage each material belongs to.
//
// content/ is generated by build_nodes.py, which is not in this repository, so a regeneration
// from an older copy of that script would put the stage fields back to fifteen stages and
// silently undo the restructure. This map is what the site actually reads, so the site stays on
// eleven stages either way. Once build_nodes.py carries the same mapping this file agrees with
// content/ and changes nothing.
const STAGE_BY_MATERIAL = {
  1: 1,
  2: 1,
  3: 2,
  4: 3,
  5: 4,
  6: 5,
  7: 6,
  8: 7,
  9: 8,
  10: 9,
  11: 10,
  12: 11,
  13: 11,
  14: 11,
  15: 11,
  16: 11,
}

// A material_id the map does not know falls back to the stage in its own file, so a new material
// still renders somewhere instead of disappearing.
export function stageFor(material) {
  const mapped = STAGE_BY_MATERIAL[material.material_id]
  return mapped === undefined ? material.stage : mapped
}
